/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SIT;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesús Ramírez
 */
public class SITGUI extends javax.swing.JFrame {

    /**
     * Creates new form SITGUI
     */
    public SITGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        miSIT=new SIT();
        jLabel1 = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        panelBuses = new javax.swing.JPanel();
        panelAgregarBuses = new javax.swing.JPanel();
        lbPlacaBusAgregar = new javax.swing.JLabel();
        tfPlacaBusAgregar = new javax.swing.JTextField();
        lbModeloBusAgregar = new javax.swing.JLabel();
        tfModeloBusAgregar = new javax.swing.JTextField();
        lbMarcaBusAgregar = new javax.swing.JLabel();
        tfMarcaBusAgregar = new javax.swing.JTextField();
        lbTipoBusAgregar = new javax.swing.JLabel();
        tfTipoBusAgregar = new javax.swing.JTextField();
        listaRutas=new String[0];
        comboRutaBusAgregar = new javax.swing.JComboBox(listaRutas);
        lbRutaBusAgregar = new javax.swing.JLabel();
        lbCapacidadBusAgregar = new javax.swing.JLabel();
        tfCapacidadBusAgregar = new javax.swing.JTextField();
        btAgregarBus = new javax.swing.JButton();
        btCargarDatos = new javax.swing.JButton();
        panelConsultarBuses = new javax.swing.JPanel();
        btListarBuses = new javax.swing.JButton();
        lbPlacaBusConsultar = new javax.swing.JLabel();
        lbModeloBusConsultar = new javax.swing.JLabel();
        lbMarcaBusConsultar = new javax.swing.JLabel();
        lbTipoBusConsultar = new javax.swing.JLabel();
        lbCapacidadBusConsultar = new javax.swing.JLabel();
        tfPlacaBusConsultar = new javax.swing.JTextField();
        tfModeloBusConsultar = new javax.swing.JTextField();
        tfMarcaBusConsultar = new javax.swing.JTextField();
        tfTipoBusConsultar = new javax.swing.JTextField();
        tfCapacidadBusConsultar = new javax.swing.JTextField();
        btConsultarBus = new javax.swing.JButton();
        lbRutaBusConsultar = new javax.swing.JLabel();
        comboRutaBusConsultar = new javax.swing.JComboBox(listaRutas);
        lbLogoBuses = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBuses = new javax.swing.JTextArea();
        panelUsuarios = new javax.swing.JPanel();
        lbLogoUsuarios = new javax.swing.JLabel();
        panelAgregarUsuarios = new javax.swing.JPanel();
        lbNumeroUsuarioAgregar = new javax.swing.JLabel();
        tfNumeroUsuarioAgregar = new javax.swing.JTextField();
        lbIdentificacionUsuarioAgregar = new javax.swing.JLabel();
        tfIdentificacionUsuarioAgregar = new javax.swing.JTextField();
        lbMarcaUsuarioAgregar = new javax.swing.JLabel();
        tfNombreUsuarioAgregar = new javax.swing.JTextField();
        lbDireccionUsuarioAgregar = new javax.swing.JLabel();
        tfDireccionUsuarioAgregar = new javax.swing.JTextField();
        lbFechaUsuarioAgregar = new javax.swing.JLabel();
        tfFechaUsuarioAgregar = new javax.swing.JTextField();
        btAgregarUsuario = new javax.swing.JButton();
        lbSaldoUsuarioAgregar = new javax.swing.JLabel();
        tfSaldoAgregar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taUsuarios = new javax.swing.JTextArea();
        panelConsultarUsuarios = new javax.swing.JPanel();
        btListarUsuarios = new javax.swing.JButton();
        lbNumeroUsuarioConsultar = new javax.swing.JLabel();
        lbIdentificacionUsuarioConsultar = new javax.swing.JLabel();
        lbNombreUsuarioConsultar = new javax.swing.JLabel();
        lbDireccionUsuarioConsultar = new javax.swing.JLabel();
        lbFechaUsuarioConsultar = new javax.swing.JLabel();
        tfNumeroUsuarioConsultar = new javax.swing.JTextField();
        tfIdentificacionUsuarioConsultar = new javax.swing.JTextField();
        tfNombreUsuarioConsultar = new javax.swing.JTextField();
        tfDireccionUsuarioConsultar = new javax.swing.JTextField();
        tfFechaUsuarioConsultar = new javax.swing.JTextField();
        btConsultarUsuario = new javax.swing.JButton();
        lbSaldoUsuarioConsultar = new javax.swing.JLabel();
        tfSaldoUsuarioConsultar = new javax.swing.JTextField();
        panelRutas = new javax.swing.JPanel();
        lbLogoRutas = new javax.swing.JLabel();
        panelAgregarRutas = new javax.swing.JPanel();
        lbCodigoRutaAgregar = new javax.swing.JLabel();
        tfCodigoRutaAgregar = new javax.swing.JTextField();
        lbNombreRutaAgregar = new javax.swing.JLabel();
        tfNombreRutaAgregar = new javax.swing.JTextField();
        lbTipoRutaAgregar = new javax.swing.JLabel();
        tfTipoRutaAgregar = new javax.swing.JTextField();
        lbDescripcionRutaAgregar = new javax.swing.JLabel();
        btAgregarRuta = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taRutas = new javax.swing.JTextArea();
        panelConsultarRutas = new javax.swing.JPanel();
        btListarRutas = new javax.swing.JButton();
        lbCodigoRutaConsultar = new javax.swing.JLabel();
        lbNombreRutaConsultar = new javax.swing.JLabel();
        lbTipoRutaConsultar = new javax.swing.JLabel();
        tfCodigoRutaConsultar = new javax.swing.JTextField();
        tfNombreRutaConsultar = new javax.swing.JTextField();
        tfTipoRutaConsultar = new javax.swing.JTextField();
        btConsultarRuta = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAgregarBuses.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar"));

        lbPlacaBusAgregar.setText("Placa");

        tfPlacaBusAgregar.setToolTipText("");

        lbModeloBusAgregar.setText("Modelo");

        lbMarcaBusAgregar.setText("Marca");

        lbTipoBusAgregar.setText("Tipo");

        lbRutaBusAgregar.setText("Ruta");

        lbCapacidadBusAgregar.setText("Capacidad");

        btAgregarBus.setText("Agregar");
        btAgregarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarBusActionPerformed(evt);
            }
        });

        btCargarDatos.setText("Cargar datos");

        javax.swing.GroupLayout panelAgregarBusesLayout = new javax.swing.GroupLayout(panelAgregarBuses);
        panelAgregarBuses.setLayout(panelAgregarBusesLayout);
        panelAgregarBusesLayout.setHorizontalGroup(
            panelAgregarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarBusesLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(panelAgregarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarBusesLayout.createSequentialGroup()
                        .addComponent(lbRutaBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboRutaBusAgregar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(214, 214, 214))
                    .addGroup(panelAgregarBusesLayout.createSequentialGroup()
                        .addGroup(panelAgregarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbTipoBusAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(lbPlacaBusAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgregarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfTipoBusAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(tfPlacaBusAgregar))
                        .addGap(18, 18, 18)
                        .addComponent(lbModeloBusAgregar)
                        .addGap(18, 18, 18)
                        .addGroup(panelAgregarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarBusesLayout.createSequentialGroup()
                                .addGroup(panelAgregarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAgregarBusesLayout.createSequentialGroup()
                                        .addComponent(lbCapacidadBusAgregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfCapacidadBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAgregarBusesLayout.createSequentialGroup()
                                        .addComponent(tfModeloBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(lbMarcaBusAgregar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfMarcaBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAgregarBusesLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btAgregarBus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCargarDatos)))
                        .addGap(20, 20, 20))))
        );
        panelAgregarBusesLayout.setVerticalGroup(
            panelAgregarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarBusesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPlacaBusAgregar)
                    .addComponent(tfPlacaBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbModeloBusAgregar)
                    .addComponent(tfModeloBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMarcaBusAgregar)
                    .addComponent(tfMarcaBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoBusAgregar)
                    .addComponent(tfTipoBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCapacidadBusAgregar)
                    .addComponent(tfCapacidadBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRutaBusAgregar)
                    .addComponent(comboRutaBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgregarBus)
                    .addComponent(btCargarDatos))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelConsultarBuses.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));

        btListarBuses.setText("Listar Buses");
        btListarBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarBusesActionPerformed(evt);
            }
        });

        lbPlacaBusConsultar.setText("Placa");

        lbModeloBusConsultar.setText("Modelo");

        lbMarcaBusConsultar.setText("Marca");

        lbTipoBusConsultar.setText("Tipo");

        lbCapacidadBusConsultar.setText("Capacidad");

        tfModeloBusConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModeloBusConsultarActionPerformed(evt);
            }
        });

        tfMarcaBusConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMarcaBusConsultarActionPerformed(evt);
            }
        });

        tfTipoBusConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTipoBusConsultarActionPerformed(evt);
            }
        });

        btConsultarBus.setText("Consultar");
        btConsultarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarBusActionPerformed(evt);
            }
        });

        lbRutaBusConsultar.setText("Ruta");

        comboRutaBusConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRutaBusConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultarBusesLayout = new javax.swing.GroupLayout(panelConsultarBuses);
        panelConsultarBuses.setLayout(panelConsultarBusesLayout);
        panelConsultarBusesLayout.setHorizontalGroup(
            panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarBusesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultarBusesLayout.createSequentialGroup()
                        .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMarcaBusConsultar)
                            .addComponent(lbTipoBusConsultar)
                            .addComponent(lbModeloBusConsultar)
                            .addComponent(lbPlacaBusConsultar))
                        .addGap(47, 47, 47)
                        .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTipoBusConsultar)
                            .addComponent(tfMarcaBusConsultar)
                            .addComponent(tfPlacaBusConsultar)
                            .addComponent(tfModeloBusConsultar))
                        .addGap(44, 44, 44))
                    .addGroup(panelConsultarBusesLayout.createSequentialGroup()
                        .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCapacidadBusConsultar)
                            .addComponent(lbRutaBusConsultar))
                        .addGap(31, 31, 31)
                        .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConsultarBusesLayout.createSequentialGroup()
                                .addComponent(tfCapacidadBusConsultar)
                                .addGap(44, 44, 44))
                            .addGroup(panelConsultarBusesLayout.createSequentialGroup()
                                .addComponent(comboRutaBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelConsultarBusesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btConsultarBus)
                        .addGap(18, 18, 18)
                        .addComponent(btListarBuses)
                        .addContainerGap())))
        );
        panelConsultarBusesLayout.setVerticalGroup(
            panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarBusesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPlacaBusConsultar)
                    .addComponent(tfPlacaBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfModeloBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbModeloBusConsultar))
                .addGap(13, 13, 13)
                .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMarcaBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMarcaBusConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoBusConsultar)
                    .addComponent(tfTipoBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCapacidadBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCapacidadBusConsultar))
                .addGap(18, 18, 18)
                .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRutaBusConsultar)
                    .addComponent(comboRutaBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelConsultarBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultarBus)
                    .addComponent(btListarBuses))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        lbLogoBuses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoSIT.png"))); // NOI18N

        taBuses.setEditable(false);
        taBuses.setColumns(20);
        taBuses.setRows(5);
        jScrollPane1.setViewportView(taBuses);

        javax.swing.GroupLayout panelBusesLayout = new javax.swing.GroupLayout(panelBuses);
        panelBuses.setLayout(panelBusesLayout);
        panelBusesLayout.setHorizontalGroup(
            panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelConsultarBuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbLogoBuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAgregarBuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        panelBusesLayout.setVerticalGroup(
            panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAgregarBuses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLogoBuses, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelConsultarBuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(24, 24, 24))
        );

        tabbedPane.addTab("Buses", panelBuses);

        lbLogoUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoSIT.png"))); // NOI18N

        panelAgregarUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar"));

        lbNumeroUsuarioAgregar.setText("Numero");

        tfNumeroUsuarioAgregar.setToolTipText("");

        lbIdentificacionUsuarioAgregar.setText("Identificacion");

        lbMarcaUsuarioAgregar.setText("Nombre");

        tfNombreUsuarioAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreUsuarioAgregarActionPerformed(evt);
            }
        });

        lbDireccionUsuarioAgregar.setText("Direccion");

        lbFechaUsuarioAgregar.setText("Fecha (D/M/A)");

        btAgregarUsuario.setText("Agregar");
        btAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarUsuarioActionPerformed(evt);
            }
        });

        lbSaldoUsuarioAgregar.setText("Saldo");

        tfSaldoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSaldoAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarUsuariosLayout = new javax.swing.GroupLayout(panelAgregarUsuarios);
        panelAgregarUsuarios.setLayout(panelAgregarUsuariosLayout);
        panelAgregarUsuariosLayout.setHorizontalGroup(
            panelAgregarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarUsuariosLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(panelAgregarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDireccionUsuarioAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNumeroUsuarioAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfDireccionUsuarioAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(tfNumeroUsuarioAgregar))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIdentificacionUsuarioAgregar)
                    .addComponent(lbFechaUsuarioAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfIdentificacionUsuarioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFechaUsuarioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelAgregarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAgregarUsuariosLayout.createSequentialGroup()
                        .addComponent(lbMarcaUsuarioAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNombreUsuarioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAgregarUsuariosLayout.createSequentialGroup()
                        .addComponent(lbSaldoUsuarioAgregar)
                        .addGap(18, 18, 18)
                        .addGroup(panelAgregarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAgregarUsuario)
                            .addComponent(tfSaldoAgregar))))
                .addGap(20, 20, 20))
        );
        panelAgregarUsuariosLayout.setVerticalGroup(
            panelAgregarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumeroUsuarioAgregar)
                    .addComponent(tfNumeroUsuarioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIdentificacionUsuarioAgregar)
                    .addComponent(tfIdentificacionUsuarioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMarcaUsuarioAgregar)
                    .addComponent(tfNombreUsuarioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccionUsuarioAgregar)
                    .addComponent(tfDireccionUsuarioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFechaUsuarioAgregar)
                    .addComponent(tfFechaUsuarioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSaldoUsuarioAgregar)
                    .addComponent(tfSaldoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAgregarUsuario)
                .addContainerGap())
        );

        taUsuarios.setEditable(false);
        taUsuarios.setColumns(20);
        taUsuarios.setRows(5);
        jScrollPane3.setViewportView(taUsuarios);

        panelConsultarUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));

        btListarUsuarios.setText("Listar Usuarios");
        btListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarUsuariosActionPerformed(evt);
            }
        });

        lbNumeroUsuarioConsultar.setText("Numero");

        lbIdentificacionUsuarioConsultar.setText("Identificacion");

        lbNombreUsuarioConsultar.setText("Nombre");

        lbDireccionUsuarioConsultar.setText("Direccion");

        lbFechaUsuarioConsultar.setText("Fecha");

        tfIdentificacionUsuarioConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdentificacionUsuarioConsultarActionPerformed(evt);
            }
        });

        tfNombreUsuarioConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreUsuarioConsultarActionPerformed(evt);
            }
        });

        tfDireccionUsuarioConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDireccionUsuarioConsultarActionPerformed(evt);
            }
        });

        btConsultarUsuario.setText("Consultar");
        btConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarUsuarioActionPerformed(evt);
            }
        });

        lbSaldoUsuarioConsultar.setText("Saldo");

        tfSaldoUsuarioConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSaldoUsuarioConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultarUsuariosLayout = new javax.swing.GroupLayout(panelConsultarUsuarios);
        panelConsultarUsuarios.setLayout(panelConsultarUsuariosLayout);
        panelConsultarUsuariosLayout.setHorizontalGroup(
            panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarUsuariosLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultarUsuariosLayout.createSequentialGroup()
                        .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFechaUsuarioConsultar)
                            .addGroup(panelConsultarUsuariosLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btConsultarUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(btListarUsuarios)))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarUsuariosLayout.createSequentialGroup()
                        .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConsultarUsuariosLayout.createSequentialGroup()
                                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombreUsuarioConsultar)
                                    .addComponent(lbDireccionUsuarioConsultar))
                                .addGap(25, 25, 25)
                                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDireccionUsuarioConsultar)
                                    .addComponent(tfNombreUsuarioConsultar)
                                    .addComponent(tfFechaUsuarioConsultar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(panelConsultarUsuariosLayout.createSequentialGroup()
                                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNumeroUsuarioConsultar)
                                    .addComponent(lbIdentificacionUsuarioConsultar)
                                    .addComponent(lbSaldoUsuarioConsultar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNumeroUsuarioConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(tfIdentificacionUsuarioConsultar)
                                    .addComponent(tfSaldoUsuarioConsultar, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(44, 44, 44))))
        );
        panelConsultarUsuariosLayout.setVerticalGroup(
            panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumeroUsuarioConsultar)
                    .addComponent(tfNumeroUsuarioConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdentificacionUsuarioConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIdentificacionUsuarioConsultar))
                .addGap(13, 13, 13)
                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreUsuarioConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreUsuarioConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccionUsuarioConsultar)
                    .addComponent(tfDireccionUsuarioConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFechaUsuarioConsultar)
                    .addComponent(tfFechaUsuarioConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSaldoUsuarioConsultar)
                    .addComponent(tfSaldoUsuarioConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultarUsuario)
                    .addComponent(btListarUsuarios))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogoUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(panelConsultarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAgregarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogoUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(panelAgregarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(panelConsultarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        tabbedPane.addTab("Usuarios", panelUsuarios);

        panelRutas.setToolTipText("");

        lbLogoRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoSIT.png"))); // NOI18N

        panelAgregarRutas.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar"));

        lbCodigoRutaAgregar.setText("Codigo");

        tfCodigoRutaAgregar.setToolTipText("");

        lbNombreRutaAgregar.setText("Nombre");

        lbTipoRutaAgregar.setText("Tipo");

        lbDescripcionRutaAgregar.setText("Descripcion");

        btAgregarRuta.setText("Agregar");
        btAgregarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarRutaActionPerformed(evt);
            }
        });

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        jScrollPane4.setViewportView(taDescripcion);

        javax.swing.GroupLayout panelAgregarRutasLayout = new javax.swing.GroupLayout(panelAgregarRutas);
        panelAgregarRutas.setLayout(panelAgregarRutasLayout);
        panelAgregarRutasLayout.setHorizontalGroup(
            panelAgregarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarRutasLayout.createSequentialGroup()
                        .addComponent(lbCodigoRutaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAgregarRuta)
                        .addGap(67, 67, 67))
                    .addGroup(panelAgregarRutasLayout.createSequentialGroup()
                        .addGroup(panelAgregarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarRutasLayout.createSequentialGroup()
                                .addComponent(lbDescripcionRutaAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4))
                            .addGroup(panelAgregarRutasLayout.createSequentialGroup()
                                .addGap(0, 44, Short.MAX_VALUE)
                                .addComponent(tfCodigoRutaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbNombreRutaAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfNombreRutaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbTipoRutaAgregar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTipoRutaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        panelAgregarRutasLayout.setVerticalGroup(
            panelAgregarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoRutaAgregar)
                    .addComponent(tfCodigoRutaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreRutaAgregar)
                    .addComponent(tfNombreRutaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTipoRutaAgregar)
                    .addComponent(tfTipoRutaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarRutasLayout.createSequentialGroup()
                        .addComponent(lbDescripcionRutaAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAgregarRuta))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        taRutas.setEditable(false);
        taRutas.setColumns(20);
        taRutas.setRows(5);
        jScrollPane2.setViewportView(taRutas);

        panelConsultarRutas.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));

        btListarRutas.setText("Listar Rutas");
        btListarRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarRutasActionPerformed(evt);
            }
        });

        lbCodigoRutaConsultar.setText("Codigo");

        lbNombreRutaConsultar.setText("Nombre");

        lbTipoRutaConsultar.setText("Tipo");

        tfNombreRutaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreRutaConsultarActionPerformed(evt);
            }
        });

        tfTipoRutaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTipoRutaConsultarActionPerformed(evt);
            }
        });

        btConsultarRuta.setText("Consultar");
        btConsultarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultarRutasLayout = new javax.swing.GroupLayout(panelConsultarRutas);
        panelConsultarRutas.setLayout(panelConsultarRutasLayout);
        panelConsultarRutasLayout.setHorizontalGroup(
            panelConsultarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarRutasLayout.createSequentialGroup()
                .addGroup(panelConsultarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultarRutasLayout.createSequentialGroup()
                        .addComponent(lbCodigoRutaConsultar)
                        .addGap(51, 51, 51)
                        .addComponent(tfCodigoRutaConsultar))
                    .addGroup(panelConsultarRutasLayout.createSequentialGroup()
                        .addGroup(panelConsultarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConsultarRutasLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btConsultarRuta)
                                .addGap(18, 18, 18)
                                .addComponent(btListarRutas))
                            .addComponent(lbTipoRutaConsultar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarRutasLayout.createSequentialGroup()
                        .addComponent(lbNombreRutaConsultar)
                        .addGap(47, 47, 47)
                        .addGroup(panelConsultarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTipoRutaConsultar)
                            .addComponent(tfNombreRutaConsultar))))
                .addContainerGap())
        );
        panelConsultarRutasLayout.setVerticalGroup(
            panelConsultarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoRutaConsultar)
                    .addComponent(tfCodigoRutaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(panelConsultarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreRutaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreRutaConsultar))
                .addGap(48, 48, 48)
                .addGroup(panelConsultarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTipoRutaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTipoRutaConsultar))
                .addGap(32, 32, 32)
                .addGroup(panelConsultarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultarRuta)
                    .addComponent(btListarRutas))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRutasLayout = new javax.swing.GroupLayout(panelRutas);
        panelRutas.setLayout(panelRutasLayout);
        panelRutasLayout.setHorizontalGroup(
            panelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbLogoRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelConsultarRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAgregarRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        panelRutasLayout.setVerticalGroup(
            panelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAgregarRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbLogoRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(panelConsultarRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        tabbedPane.addTab("Rutas", panelRutas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Actualiza los elementos en el comboBox
    public void setcombo(String[] lista,JComboBox combo ){
        lista=new String[miSIT.numeroRutas()];
        for(int i=0;i<lista.length;i++){
            Ruta ruta=(Ruta) miSIT.rutas.get(i);
            if(!(ruta.getNombre().equals(combo.getItemAt(i)))){
            combo.addItem(ruta.getNombre());
            miSIT.rutas.set(i, ruta);
            }
        }
    }

    private void btListarBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarBusesActionPerformed
        taBuses.setText("");
        String listaBuses="";
        try{
        String ruta =comboRutaBusConsultar.getSelectedItem().toString();
        listaBuses=miSIT.listarBusesRuta();
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "No hay buses");
        }
        taBuses.setText(listaBuses);
    }//GEN-LAST:event_btListarBusesActionPerformed

    private void tfModeloBusConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModeloBusConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfModeloBusConsultarActionPerformed

    private void tfMarcaBusConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMarcaBusConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMarcaBusConsultarActionPerformed

    private void tfTipoBusConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTipoBusConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTipoBusConsultarActionPerformed

    private void btListarRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarRutasActionPerformed
        // TODO add your handling code here:
        taRutas.setText("");
        String listaRutas=miSIT.listarRutas();
        taRutas.setText(listaRutas);
    }//GEN-LAST:event_btListarRutasActionPerformed

    private void tfNombreRutaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreRutaConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreRutaConsultarActionPerformed

    private void tfTipoRutaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTipoRutaConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTipoRutaConsultarActionPerformed

    private void btListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarUsuariosActionPerformed
        // TODO add your handling code here:
        taUsuarios.setText("");
        String listaUsuarios="";
        listaUsuarios=miSIT.listarUsuarios();
        taUsuarios.setText(listaUsuarios);

    }//GEN-LAST:event_btListarUsuariosActionPerformed

    private void tfIdentificacionUsuarioConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdentificacionUsuarioConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdentificacionUsuarioConsultarActionPerformed

    private void tfNombreUsuarioConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreUsuarioConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreUsuarioConsultarActionPerformed

    private void tfDireccionUsuarioConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDireccionUsuarioConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDireccionUsuarioConsultarActionPerformed

    private void comboRutaBusConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRutaBusConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRutaBusConsultarActionPerformed

    private void tfSaldoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSaldoAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSaldoAgregarActionPerformed

    private void tfSaldoUsuarioConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSaldoUsuarioConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSaldoUsuarioConsultarActionPerformed

    private void tfNombreUsuarioAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreUsuarioAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreUsuarioAgregarActionPerformed

    private void btAgregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarRutaActionPerformed
        String codigo=tfCodigoRutaAgregar.getText();
        String nombre=tfNombreRutaAgregar.getText();
        String tipo=tfTipoRutaAgregar.getText();
        String descripcion=taDescripcion.getText();

        Ruta ruta=new Ruta();
        ruta.setCodigo(codigo);
        ruta.setDescripcion(descripcion);
        ruta.setNombre(nombre);
        ruta.setTipo(tipo);
        miSIT.agregarRuta(ruta);

        tfCodigoRutaAgregar.setText("");
        tfNombreRutaAgregar.setText("");
        tfTipoRutaAgregar.setText("");
        taDescripcion.setText("");

        this.setcombo(listaRutas, comboRutaBusAgregar);
        this.setcombo(listaRutas, comboRutaBusConsultar);

    }//GEN-LAST:event_btAgregarRutaActionPerformed

    private void btAgregarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarBusActionPerformed
        // TODO add your handling code here:
        String placa=tfPlacaBusAgregar.getText();
        String modelo=tfModeloBusAgregar.getText();
        String marca=tfMarcaBusAgregar.getText();
        String tipo=tfTipoBusAgregar.getText();
        String capacidad=tfCapacidadBusAgregar.getText();

        Bus bus =new Bus();
        bus.setPlaca(placa);
        bus.setModelo(modelo);
        bus.setMarca(marca);
        bus.setTipo(tipo);
        bus.setCapacidad(capacidad);

        tfPlacaBusAgregar.setText("");
        tfModeloBusAgregar.setText("");
        tfMarcaBusAgregar.setText("");
        tfTipoBusAgregar.setText("");
        tfCapacidadBusAgregar.setText("");
        try{
        String ruta=comboRutaBusAgregar.getSelectedItem().toString();
        miSIT.agregarBusRuta(bus,miSIT.getRuta(ruta));
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Debe crear y seleccionar una ruta antes de crear un bus");
        }
    }//GEN-LAST:event_btAgregarBusActionPerformed

    private void btConsultarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarBusActionPerformed
        // TODO add your handling code here:
        taBuses.setText("");
        String placa =tfPlacaBusConsultar.getText();
        String modelo =tfModeloBusConsultar.getText();
        String marca =tfMarcaBusConsultar.getText();
        String tipo =tfTipoBusConsultar.getText();
        String capacidad =tfCapacidadBusConsultar.getText();
        try{
        String ruta =comboRutaBusConsultar.getSelectedItem().toString();

        tfPlacaBusConsultar.setText("");
        tfModeloBusConsultar.setText("");
        tfMarcaBusConsultar.setText("");
        tfTipoBusConsultar.setText("");
        tfCapacidadBusConsultar.setText("");

        String listaBuses=miSIT.consultarBusRuta(placa,modelo,marca,tipo,capacidad,miSIT.getRuta(ruta));

        taBuses.setText(listaBuses);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Error....debe crear una ruta antes de consultar");
        }
    }//GEN-LAST:event_btConsultarBusActionPerformed

    private void btAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarUsuarioActionPerformed
        // TODO add your handling code here:
        String numero=tfNumeroUsuarioAgregar.getText();
        String identificacion=tfIdentificacionUsuarioAgregar.getText();
        String nombre=tfNombreUsuarioAgregar.getText();
        String direccion=tfDireccionUsuarioAgregar.getText();
        String fecha=tfFechaUsuarioAgregar.getText();

        tfNumeroUsuarioAgregar.setText("");
        tfIdentificacionUsuarioAgregar.setText("");
        tfNombreUsuarioAgregar.setText("");
        tfDireccionUsuarioAgregar.setText("");
        tfFechaUsuarioAgregar.setText("");
        try{
        double saldo=Double.parseDouble(tfSaldoAgregar.getText());
        tfSaldoAgregar.setText("");
        Usuario usuario =new Usuario();
        usuario.setNumero(numero);
        usuario.setIdentificacion(identificacion);
        usuario.setNombre(nombre);
        usuario.setDireccion(direccion);
        usuario.setFecha(fecha);
        usuario.setSaldo(saldo);

        miSIT.agregarUsuario(usuario);
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El valor ingresado en saldo debe ser un número (0-9)");
        }
    }//GEN-LAST:event_btAgregarUsuarioActionPerformed

    private void btConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarUsuarioActionPerformed
        // TODO add your handling code here:
        taUsuarios.setText("");
        String numero=tfNumeroUsuarioConsultar.getText();
        String identificacion=tfIdentificacionUsuarioConsultar.getText();
        String nombre=tfNombreUsuarioConsultar.getText();
        String direccion=tfDireccionUsuarioConsultar.getText();
        String fecha=tfFechaUsuarioConsultar.getText();

        tfNumeroUsuarioConsultar.setText("");
        tfIdentificacionUsuarioConsultar.setText("");
        tfNombreUsuarioConsultar.setText("");
        tfDireccionUsuarioConsultar.setText("");
        tfFechaUsuarioConsultar.setText("");
        try{
        double saldo=Double.parseDouble(tfSaldoUsuarioConsultar.getText());
        tfSaldoUsuarioConsultar.setText("");
        String listaUsuario=miSIT.consultarUsuario(numero, identificacion, nombre, direccion, fecha, saldo);
        taUsuarios.setText(listaUsuario);
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El valor ingresado en saldo debe ser un número (0-9)");
        }
    }//GEN-LAST:event_btConsultarUsuarioActionPerformed

    private void btConsultarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarRutaActionPerformed
        // TODO add your handling code here:
        taRutas.setText("");
        String codigo=tfCodigoRutaConsultar.getText();
        String nombre=tfNombreRutaConsultar.getText();
        String tipo=tfTipoRutaConsultar.getText();

        tfCodigoRutaConsultar.setText("");
        tfNombreRutaConsultar.setText("");
        tfTipoRutaConsultar.setText("");

        String listaRutas=miSIT.consultarRuta(codigo, nombre, tipo);
        taRutas.setText(listaRutas);

    }//GEN-LAST:event_btConsultarRutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SITGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SITGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SITGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SITGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SITGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    SIT miSIT;
    String listaRutas[];
    private javax.swing.JButton btAgregarBus;
    private javax.swing.JButton btAgregarRuta;
    private javax.swing.JButton btAgregarUsuario;
    private javax.swing.JButton btCargarDatos;
    private javax.swing.JButton btConsultarBus;
    private javax.swing.JButton btConsultarRuta;
    private javax.swing.JButton btConsultarUsuario;
    private javax.swing.JButton btListarBuses;
    private javax.swing.JButton btListarRutas;
    private javax.swing.JButton btListarUsuarios;
    private javax.swing.JComboBox comboRutaBusAgregar;
    private javax.swing.JComboBox comboRutaBusConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbCapacidadBusAgregar;
    private javax.swing.JLabel lbCapacidadBusConsultar;
    private javax.swing.JLabel lbCodigoRutaAgregar;
    private javax.swing.JLabel lbCodigoRutaConsultar;
    private javax.swing.JLabel lbDescripcionRutaAgregar;
    private javax.swing.JLabel lbDireccionUsuarioAgregar;
    private javax.swing.JLabel lbDireccionUsuarioConsultar;
    private javax.swing.JLabel lbFechaUsuarioAgregar;
    private javax.swing.JLabel lbFechaUsuarioConsultar;
    private javax.swing.JLabel lbIdentificacionUsuarioAgregar;
    private javax.swing.JLabel lbIdentificacionUsuarioConsultar;
    private javax.swing.JLabel lbLogoBuses;
    private javax.swing.JLabel lbLogoRutas;
    private javax.swing.JLabel lbLogoUsuarios;
    private javax.swing.JLabel lbMarcaBusAgregar;
    private javax.swing.JLabel lbMarcaBusConsultar;
    private javax.swing.JLabel lbMarcaUsuarioAgregar;
    private javax.swing.JLabel lbModeloBusAgregar;
    private javax.swing.JLabel lbModeloBusConsultar;
    private javax.swing.JLabel lbNombreRutaAgregar;
    private javax.swing.JLabel lbNombreRutaConsultar;
    private javax.swing.JLabel lbNombreUsuarioConsultar;
    private javax.swing.JLabel lbNumeroUsuarioAgregar;
    private javax.swing.JLabel lbNumeroUsuarioConsultar;
    private javax.swing.JLabel lbPlacaBusAgregar;
    private javax.swing.JLabel lbPlacaBusConsultar;
    private javax.swing.JLabel lbRutaBusAgregar;
    private javax.swing.JLabel lbRutaBusConsultar;
    private javax.swing.JLabel lbSaldoUsuarioAgregar;
    private javax.swing.JLabel lbSaldoUsuarioConsultar;
    private javax.swing.JLabel lbTipoBusAgregar;
    private javax.swing.JLabel lbTipoBusConsultar;
    private javax.swing.JLabel lbTipoRutaAgregar;
    private javax.swing.JLabel lbTipoRutaConsultar;
    private javax.swing.JPanel panelAgregarBuses;
    private javax.swing.JPanel panelAgregarRutas;
    private javax.swing.JPanel panelAgregarUsuarios;
    private javax.swing.JPanel panelBuses;
    private javax.swing.JPanel panelConsultarBuses;
    private javax.swing.JPanel panelConsultarRutas;
    private javax.swing.JPanel panelConsultarUsuarios;
    private javax.swing.JPanel panelRutas;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JTextArea taBuses;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextArea taRutas;
    private javax.swing.JTextArea taUsuarios;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField tfCapacidadBusAgregar;
    private javax.swing.JTextField tfCapacidadBusConsultar;
    private javax.swing.JTextField tfCodigoRutaAgregar;
    private javax.swing.JTextField tfCodigoRutaConsultar;
    private javax.swing.JTextField tfDireccionUsuarioAgregar;
    private javax.swing.JTextField tfDireccionUsuarioConsultar;
    private javax.swing.JTextField tfFechaUsuarioAgregar;
    private javax.swing.JTextField tfFechaUsuarioConsultar;
    private javax.swing.JTextField tfIdentificacionUsuarioAgregar;
    private javax.swing.JTextField tfIdentificacionUsuarioConsultar;
    private javax.swing.JTextField tfMarcaBusAgregar;
    private javax.swing.JTextField tfMarcaBusConsultar;
    private javax.swing.JTextField tfModeloBusAgregar;
    private javax.swing.JTextField tfModeloBusConsultar;
    private javax.swing.JTextField tfNombreRutaAgregar;
    private javax.swing.JTextField tfNombreRutaConsultar;
    private javax.swing.JTextField tfNombreUsuarioAgregar;
    private javax.swing.JTextField tfNombreUsuarioConsultar;
    private javax.swing.JTextField tfNumeroUsuarioAgregar;
    private javax.swing.JTextField tfNumeroUsuarioConsultar;
    private javax.swing.JTextField tfPlacaBusAgregar;
    private javax.swing.JTextField tfPlacaBusConsultar;
    private javax.swing.JTextField tfSaldoAgregar;
    private javax.swing.JTextField tfSaldoUsuarioConsultar;
    private javax.swing.JTextField tfTipoBusAgregar;
    private javax.swing.JTextField tfTipoBusConsultar;
    private javax.swing.JTextField tfTipoRutaAgregar;
    private javax.swing.JTextField tfTipoRutaConsultar;
    // End of variables declaration//GEN-END:variables
}
