/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SIT;

/**
 *
 * @author Jesús Ramírez
 */
public class SITGUI extends javax.swing.JFrame {

    /**
     * Creates new form SITGUI
     */
    public SITGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        panelRutas = new javax.swing.JPanel();
        panelBuses = new javax.swing.JPanel();
        panelAgregarBus = new javax.swing.JPanel();
        lbAgregarPlacaBus = new javax.swing.JLabel();
        tfPlacaAgregar = new javax.swing.JTextField();
        lbModeloBusAgregar = new javax.swing.JLabel();
        tfModeloBusAgregar = new javax.swing.JTextField();
        lbMarcaBusAgregar = new javax.swing.JLabel();
        tfMarcaBusAgregar = new javax.swing.JTextField();
        lbTipoBusAgregar = new javax.swing.JLabel();
        tfTipoBusAgregar = new javax.swing.JTextField();
        comboRutaBusAgregar = new javax.swing.JComboBox<>();
        lbRutaBusAgregar = new javax.swing.JLabel();
        lbCapacidadBusAgregar = new javax.swing.JLabel();
        tfCapacidadBusAgregar = new javax.swing.JTextField();
        btAgregarBus = new javax.swing.JButton();
        panelConsultarBus = new javax.swing.JPanel();
        btListarBuses = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfPlacaBusConsultar = new javax.swing.JTextField();
        tfModeloBusConsultar = new javax.swing.JTextField();
        tfMarcaBusConsultar = new javax.swing.JTextField();
        tfTipoBusConsultar = new javax.swing.JTextField();
        tfCapacidadBusConsultar = new javax.swing.JTextField();
        btConsultarBus = new javax.swing.JButton();
        lbRutaBus = new javax.swing.JLabel();
        comboRutaBusConsultar = new javax.swing.JComboBox<>();
        lbCodigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfBuses = new javax.swing.JTextArea();
        panelUsuarios = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRutas.setToolTipText("");

        javax.swing.GroupLayout panelRutasLayout = new javax.swing.GroupLayout(panelRutas);
        panelRutas.setLayout(panelRutasLayout);
        panelRutasLayout.setHorizontalGroup(
            panelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        panelRutasLayout.setVerticalGroup(
            panelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Rutas", panelRutas);

        panelAgregarBus.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar"));

        lbAgregarPlacaBus.setText("Placa");

        tfPlacaAgregar.setToolTipText("");

        lbModeloBusAgregar.setText("Modelo");

        lbMarcaBusAgregar.setText("Marca");

        lbTipoBusAgregar.setText("Tipo");

        lbRutaBusAgregar.setText("Ruta");

        lbCapacidadBusAgregar.setText("Capacidad");

        btAgregarBus.setText("Agregar");

        javax.swing.GroupLayout panelAgregarBusLayout = new javax.swing.GroupLayout(panelAgregarBus);
        panelAgregarBus.setLayout(panelAgregarBusLayout);
        panelAgregarBusLayout.setHorizontalGroup(
            panelAgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarBusLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelAgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarBusLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbRutaBusAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(comboRutaBusAgregar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(btAgregarBus)
                        .addGap(67, 67, 67))
                    .addGroup(panelAgregarBusLayout.createSequentialGroup()
                        .addGroup(panelAgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarBusLayout.createSequentialGroup()
                                .addComponent(lbTipoBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfTipoBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAgregarBusLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbAgregarPlacaBus)
                                .addGap(18, 18, 18)
                                .addComponent(tfPlacaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbModeloBusAgregar)))
                        .addGap(18, 18, 18)
                        .addGroup(panelAgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarBusLayout.createSequentialGroup()
                                .addComponent(lbCapacidadBusAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCapacidadBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAgregarBusLayout.createSequentialGroup()
                                .addComponent(tfModeloBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lbMarcaBusAgregar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfMarcaBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        panelAgregarBusLayout.setVerticalGroup(
            panelAgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarBusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAgregarPlacaBus)
                    .addComponent(tfPlacaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbModeloBusAgregar)
                    .addComponent(tfModeloBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMarcaBusAgregar)
                    .addComponent(tfMarcaBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoBusAgregar)
                    .addComponent(tfTipoBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCapacidadBusAgregar)
                    .addComponent(tfCapacidadBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRutaBusAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRutaBusAgregar)
                    .addComponent(btAgregarBus))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelConsultarBus.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));

        btListarBuses.setText("Listar Buses");
        btListarBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarBusesActionPerformed(evt);
            }
        });

        jLabel2.setText("Placa");

        jLabel3.setText("Modelo");

        jLabel4.setText("Marca");

        jLabel5.setText("Tipo");

        jLabel6.setText("Capacidad");

        tfModeloBusConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModeloBusConsultarActionPerformed(evt);
            }
        });

        tfMarcaBusConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMarcaBusConsultarActionPerformed(evt);
            }
        });

        tfTipoBusConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTipoBusConsultarActionPerformed(evt);
            }
        });

        btConsultarBus.setText("Consultar");

        lbRutaBus.setText("Ruta");

        javax.swing.GroupLayout panelConsultarBusLayout = new javax.swing.GroupLayout(panelConsultarBus);
        panelConsultarBus.setLayout(panelConsultarBusLayout);
        panelConsultarBusLayout.setHorizontalGroup(
            panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarBusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarBusLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btConsultarBus)
                        .addGap(18, 18, 18)
                        .addComponent(btListarBuses)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelConsultarBusLayout.createSequentialGroup()
                        .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConsultarBusLayout.createSequentialGroup()
                                .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(56, 56, 56)
                                .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTipoBusConsultar)
                                    .addComponent(tfMarcaBusConsultar)))
                            .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelConsultarBusLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(60, 60, 60)
                                    .addComponent(tfPlacaBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelConsultarBusLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(51, 51, 51)
                                    .addComponent(tfModeloBusConsultar))))
                        .addGap(44, 44, 44))
                    .addGroup(panelConsultarBusLayout.createSequentialGroup()
                        .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lbRutaBus))
                        .addGap(35, 35, 35)
                        .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConsultarBusLayout.createSequentialGroup()
                                .addComponent(tfCapacidadBusConsultar)
                                .addGap(44, 44, 44))
                            .addGroup(panelConsultarBusLayout.createSequentialGroup()
                                .addComponent(comboRutaBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        panelConsultarBusLayout.setVerticalGroup(
            panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarBusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPlacaBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfModeloBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMarcaBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTipoBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfCapacidadBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRutaBusConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRutaBus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConsultarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultarBus)
                    .addComponent(btListarBuses))
                .addContainerGap())
        );

        lbCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoSIT.png"))); // NOI18N

        tfBuses.setEditable(false);
        tfBuses.setColumns(20);
        tfBuses.setRows(5);
        jScrollPane1.setViewportView(tfBuses);

        javax.swing.GroupLayout panelBusesLayout = new javax.swing.GroupLayout(panelBuses);
        panelBuses.setLayout(panelBusesLayout);
        panelBusesLayout.setHorizontalGroup(
            panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelConsultarBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAgregarBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        panelBusesLayout.setVerticalGroup(
            panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAgregarBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBusesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbCodigo)))
                .addGap(18, 18, 18)
                .addGroup(panelBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelConsultarBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(30, 30, 30))
        );

        tabbedPane.addTab("Buses", panelBuses);

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Usuarios", panelUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btListarBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarBusesActionPerformed
        tfBuses.setText("Prueba\nPrueba\nPrueba\nPrueba\nPrueba\nPrueba\nPrueba\nPrueba\nPrueba\nPrueba\nPrueba\nPrueba\nPrueba\nPrueba\nPrueba\n");
    }//GEN-LAST:event_btListarBusesActionPerformed

    private void tfModeloBusConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModeloBusConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfModeloBusConsultarActionPerformed

    private void tfMarcaBusConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMarcaBusConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMarcaBusConsultarActionPerformed

    private void tfTipoBusConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTipoBusConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTipoBusConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SITGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SITGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SITGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SITGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SITGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarBus;
    private javax.swing.JButton btConsultarBus;
    private javax.swing.JButton btListarBuses;
    private javax.swing.JComboBox<String> comboRutaBusAgregar;
    private javax.swing.JComboBox<String> comboRutaBusConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAgregarPlacaBus;
    private javax.swing.JLabel lbCapacidadBusAgregar;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbMarcaBusAgregar;
    private javax.swing.JLabel lbModeloBusAgregar;
    private javax.swing.JLabel lbRutaBus;
    private javax.swing.JLabel lbRutaBusAgregar;
    private javax.swing.JLabel lbTipoBusAgregar;
    private javax.swing.JPanel panelAgregarBus;
    private javax.swing.JPanel panelBuses;
    private javax.swing.JPanel panelConsultarBus;
    private javax.swing.JPanel panelRutas;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextArea tfBuses;
    private javax.swing.JTextField tfCapacidadBusAgregar;
    private javax.swing.JTextField tfCapacidadBusConsultar;
    private javax.swing.JTextField tfMarcaBusAgregar;
    private javax.swing.JTextField tfMarcaBusConsultar;
    private javax.swing.JTextField tfModeloBusAgregar;
    private javax.swing.JTextField tfModeloBusConsultar;
    private javax.swing.JTextField tfPlacaAgregar;
    private javax.swing.JTextField tfPlacaBusConsultar;
    private javax.swing.JTextField tfTipoBusAgregar;
    private javax.swing.JTextField tfTipoBusConsultar;
    // End of variables declaration//GEN-END:variables
}
